version: '2'
services:
  mongo:
    image: mongo
    cpu_shares: 100
    mem_limit: 240000000
    ports:
      - "27017:27017"
    volumes:
      - /mongo/db:/data/db
  web:
    image: fabisappzoo/bookingmanager
    environment:
      - ENV_URL=http://booking.alaskapirate.de
      - ENV_PORT=80
      - ENV_MONGO_URI=mongodb://mongo/test
      - CRON_TIMER=30 * * * * *
      - CRON_TIMER_OLD=* 30 8 * * *
      - MAIL_SENDER="Alaska Pirate Booking" <booking@alaskapirate.de>
      - MAIL_REPORT_RECIPIENT=fabi.fink@gmail.com
      - MAIL_BCC=fabi@alaskapirate.de
      - DAYS_UNTIL_DEADLINE=30
    cpu_shares: 100
    mem_limit: 240000000
    command: "npm start"
    links:
      - mongo
    ports:
      - "80:80"
