mongo:
  image: mongo
  volumes:
    - ./data/db:/data/db
  ports:
    - "27017:27017"
web:
  build: .
  command: "npm start"
  environment:
    - ENV_URL=http://localhost/
  links:
    - mongo
  ports:
    - "80:80"
  volumes:
    - .:/usr/src/app
