mongo:
  image: mongo
  volumes:
    - ./data/db:/data/db
  ports:
    - "27017:27017"
web:
  build: .
  command: "npm start"
  links:
    - mongo
  ports:
    - "8888:8888"
  volumes:
    - .:/usr/src/app
