mongo:
  image: mongo
  volumes:
    - ./data/db:/data/db
  ports:
    - "27017:27017"
web:
  build: .
  command: "npm start"
  environment:
    - ENV_URL=http://localhost
    - ENV_PORT=80
    - ENV_MONGO_URI=mongodb://mongo/test
    - CRON_TIMER=20 * * * * *
    - MAIL_REPORT_RECIPIENT=booking@stereo-satellite.de
  links:
    - mongo
  ports:
    - "80:80"
  volumes:
    - .:/usr/src/app
